### PR TITLE
use ping instead of arping

### PR DESCRIPTION
**Pull request by alexdpunkt**
Edited the script to use ping instead of arping because arping didn't work reliably on my network (Timeout issues). Maybe one could implement a checkbox in the plugin configuration page to switch between ping and arping if necessary.

### CODE REVIEW

**Comment by Gagi2k** [comment]
Could you create a bugreport instead and provide more information on why it is needed ? ping doesn't work for iphones, which is the reason arping is used, but i'm eager to know more in order to support you on the problem.

**Comment by alexdpunkt** [comment]
I don't know the reason why it fails, the output is as follows:  

> loxberry@loxberry:~ $ sudo /usr/sbin/arping -W 0.0002 -C1 -c5000 8d:b8:a4:74:d2:84 -i eth0
> ARPING 8d:b8:a4:74:d2:84
> Timeout
[5000 times...]
> Timeout
> 
> --- 8d:b8:a4:74:d2:84 statistics ---
> 5000 packets transmitted, 0 packets received, 100% unanswered (0 extra)

The MAC/IP Address is visible in `arp -a` , what could be the problem here?

I could create a pull request where simply both testing methods would be implemented, as a fallback if one fails. Maybe via a Checkbox in the plugin page "use ping as a fallback".

**Comment by Gagi2k** [comment]
Mhh, are you using any special network enironment ? E.g. vlans ? Is this running on a raspberry-pi ? Or are you using a virtualmachine or docker container ?

I've had similar problems in the beginning when running loxberry inside a virtual machine, that's why i ask.

Have you tried specifing an ip-address in addition to the mac address ? I'm not sure why but arping seems to work better with ip addresses for some devices.

**Comment by Gagi2k** [comment]
I just checked it here and some of my devices reply to mac arpings directly some others just to ones using the ip-address.

In the arping documentation they state that it's up to the host whether to answer a broadcast ping on a MAC...
So if pinging the ip-address works for you, i guess we could make it more smart and try to find the ip-address if not specified.

**Comment by Gagi2k** [comment]
Hi,

i'm closing this pull-request now.

I've updated the scanner a bit and i think i also know why arping didn't work for you. Relying just on the mac address using arping doesn't work reliable for all devices. Before i trusted  in the users to also add an ip address in addition to the mac addresses, so this could be checked first, but similar to your patch i'm now resolving the ip address before trying to ping it.

In addition i also added support to make the ping command configurable and added support for ping as well. So it would be great if you could give the new pre-release a try and check whether arping works for you now and if not, whether the new ping option works then ;-)

https://github.com/Gagi2k/LoxBerry-Plugin-WifiScanner/releases/tag/v2.2

**Pull request closed without merging**
